-- Milestone 3: tasks and recurrence (brief sections 6.4 and 25).

-- The task as the supervisor set it up.
CREATE TABLE tasks (
  id                   uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id           uuid NOT NULL REFERENCES companies(id),
  site_id              uuid NOT NULL REFERENCES sites(id),
  title                text NOT NULL,
  instructions         text NOT NULL DEFAULT '',
  -- A task is for one officer, or for a post (the device at that post, whoever is on duty there).
  assignee_type        text NOT NULL CHECK (assignee_type IN ('employee','post')),
  assignee_employee_id uuid REFERENCES employees(id),
  assignee_device_id   uuid REFERENCES devices(id),
  recurrence           text NOT NULL CHECK (recurrence IN ('once','daily','weekly','monthly')),
  start_date           date NOT NULL,
  end_date             date,
  time_required        boolean NOT NULL DEFAULT false,
  due_time             time,
  photo_required       boolean NOT NULL DEFAULT false,
  active               boolean NOT NULL DEFAULT true,
  -- Occurrences exist up to this date; the scheduler continues from the day after.
  generated_through    date,
  created_by           uuid REFERENCES users(id),
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now(),
  CHECK ((assignee_type = 'employee') = (assignee_employee_id IS NOT NULL)),
  CHECK ((assignee_type = 'post') = (assignee_device_id IS NOT NULL)),
  CHECK (time_required = (due_time IS NOT NULL))
);
CREATE INDEX tasks_site ON tasks (site_id);

-- One row per date the task falls on. Generated by the server on schedule,
-- whether or not earlier ones were done. Keeps a copy of the task as it was.
CREATE TABLE task_occurrences (
  id                    uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  company_id            uuid NOT NULL REFERENCES companies(id),
  task_id               uuid NOT NULL REFERENCES tasks(id),
  site_id               uuid NOT NULL REFERENCES sites(id),
  occurrence_date       date NOT NULL,
  title                 text NOT NULL,
  instructions          text NOT NULL,
  due_time              time,
  photo_required        boolean NOT NULL,
  assignee_type         text NOT NULL,
  assignee_employee_id  uuid REFERENCES employees(id),
  assignee_device_id    uuid REFERENCES devices(id),
  state                 text NOT NULL DEFAULT 'open'
                          CHECK (state IN ('open','completed','could_not_complete','missed','cancelled')),
  done_by               uuid REFERENCES employees(id),
  done_at               timestamptz,
  comment               text NOT NULL DEFAULT '',
  cannot_reason         text CHECK (cannot_reason IN ('equipment_unavailable','access_unavailable','emergency',
                                                      'supervisor_instruction','other')),
  photo_key             text,
  photo_content_type    text,
  photo_pending         boolean NOT NULL DEFAULT false,
  missed_at             timestamptz,
  -- A supervisor's review of "could not complete": accepted means no penalty.
  review                text CHECK (review IN ('accepted','not_accepted')),
  reviewed_by           uuid REFERENCES users(id),
  reviewed_at           timestamptz,
  review_note           text,
  created_at            timestamptz NOT NULL DEFAULT now(),
  UNIQUE (task_id, occurrence_date)
);
CREATE INDEX task_occurrences_site_date ON task_occurrences (site_id, occurrence_date);
CREATE INDEX task_occurrences_open ON task_occurrences (occurrence_date) WHERE state = 'open';

-- Everything that happened to an occurrence. Append-only.
CREATE TABLE task_history (
  id             bigserial PRIMARY KEY,
  company_id     uuid NOT NULL REFERENCES companies(id),
  occurrence_id  uuid NOT NULL REFERENCES task_occurrences(id),
  at             timestamptz NOT NULL,
  received_at    timestamptz NOT NULL DEFAULT now(),
  actor_type     text NOT NULL CHECK (actor_type IN ('user','employee','system')),
  actor_id       uuid,
  actor_label    text NOT NULL DEFAULT '',
  action         text NOT NULL,
  note           text NOT NULL DEFAULT '',
  -- Device actions carry their own ID so a retry never records twice.
  event_id       uuid UNIQUE,
  late_synced    boolean NOT NULL DEFAULT false,
  drift_flagged  boolean NOT NULL DEFAULT false
);
CREATE INDEX task_history_occurrence ON task_history (occurrence_id, at);
CREATE TRIGGER task_history_immutable BEFORE UPDATE OR DELETE ON task_history
  FOR EACH ROW EXECUTE FUNCTION forbid_change();

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['tasks','task_occurrences','task_history'] LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('CREATE POLICY tenant ON %I USING (company_id = app_company_id())
                    WITH CHECK (company_id = app_company_id())', t);
  END LOOP;
END $$;

-- The scheduler works company by company; this is the only cross-company
-- information it can see.
CREATE FUNCTION scheduler_company_ids() RETURNS SETOF uuid
LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$
  SELECT id FROM companies
$$;
REVOKE ALL ON FUNCTION scheduler_company_ids() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION scheduler_company_ids() TO onpar_app;

GRANT SELECT, INSERT, UPDATE ON tasks, task_occurrences TO onpar_app;
GRANT SELECT, INSERT ON task_history TO onpar_app;
GRANT USAGE ON SEQUENCE task_history_id_seq TO onpar_app;
